version: "3.8"

services:
  db:
    image: postgres:16
    container_name: odoo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: supersegura
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:17.0
    container_name: odoo_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: supersegura
      ADMIN_PASSWD: admin_master_password_superseguro
      TZ: America/Argentina/Buenos_Aires
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addo
